ARG JENKINS_VER=2.73.2
ARG JENKINS_REL=1

FROM target/jenkins-docker-master:${JENKINS_VER}-${JENKINS_REL}
COPY files/debug_logs.groovy /usr/share/jenkins/ref/init.groovy.d/debug_logs.groovy
COPY files/debug_logging.properties /usr/share/jenkins/debug_logging.properties
